# Generated by Django 2.1.3 on 2018-11-25 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0003_answer_like_am'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='можно ли достать'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='можно ли достать'),
        ),
        migrations.AlterField(
            model_name='like',
            name='question',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ask.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(default="i've got a problem", max_length=10000, verbose_name='full text'),
        ),
    ]
