# Generated by Django 2.1.3 on 2018-11-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0004_auto_20181125_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='upload',
            field=models.ImageField(default='index.png', upload_to='%Y/%m/%d/'),
        ),
    ]
